name: Production

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install CF CLI
      run: |
        ./ci/install_cf_cli.sh
    - name: Install Hugo
      run: |
        ./ci/install_hugo.sh
    - name: Build & Push
      env:
        CF_API: https://api.run.pivotal.io
        CF_USERNAME: ${{ secrets.pws_username }}
        CF_PASSWORD: ${{ secrets.pws_password}}
        CF_ORG: pivotal
        CF_SPACE: blog
      run: |
        ./ci/build_hugo.sh
        ./ci/cf_login.sh

        cf push
