name: Pull Request Opened

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install CF CLI
      run: |
        ./ci/install_cf_cli.sh
    - name: Install Hugo
      run: |
        ./ci/install_hugo.sh
    - name: Build
      env:
        CF_API: https://api.run.pivotal.io
        CF_USERNAME: ${{ secrets.pws_username }}
        CF_PASSWORD: ${{ secrets.pws_password}}
        CF_ORG: pivotal
        CF_SPACE: blog
      run: |
        source ./ci/pr_number.sh

        ./ci/build_hugo.sh
        ./ci/cf_login.sh

        cf push -f manifest-pr.yml --var pr-number=$PR_NUMBER
