name: Pull Request Closed

on:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Clean Up
      env:
        CF_API: https://api.run.pivotal.io
        CF_USERNAME: ${{ secrets.pws_username }}
        CF_PASSWORD: ${{ secrets.pws_password}}
        CF_ORG: pivotal
        CF_SPACE: blog
      run: |
        source ./ci/pr_number.sh

        ./ci/cf_login.sh

        cf delete pivotal-blog-pr-${PR_NUMBER} -r -f
